In [1]:
import numpy as np

In [2]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_grad(x):
    return x * (1 - x)

In [4]:
# Setting training iterations
epoch = 1000

# Setting learning rate (eta)
eta = 0.2

# Number of features in data set
input_neurons = 2

# Number of hidden layers neurons
hidden_neurons = 3

# Number of neurons at output layer
output_neurons = 1

In [5]:
# Weight and bias - Random initialization
wh = np.random.uniform(size=(input_neurons, hidden_neurons))  # 2x3
bh = np.random.uniform(size=(1, hidden_neurons))  # 1x3
wout = np.random.uniform(size=(hidden_neurons, output_neurons))  # 1x1
bout = np.random.uniform(size=(1, output_neurons))

In [6]:
for i in range(epoch):
    # Forward Propogation
    h_ip = np.dot(X, wh) + bh  # Dot product + Bias
    h_act = sigmoid(h_ip)  # Activation function
    o_ip = np.dot(h_act, wout) + bout
    output = sigmoid(o_ip)

# Backpropagation

# Error at output layer
Eo = y - output
outgrad = sigmoid_grad(output)
d_output = Eo * outgrad

# Error at Hidden layer
Eh = d_output.dot(wout.T)  # .T means transpose
hiddengrad = sigmoid_grad(h_act)
# How much hidden layer weights contributed to error
d_hidden = Eh * hiddengrad
wout = h_act.T.dot(d_output) * eta
# Dot product of next layer error and current layer op
wh = X.T.dot(d_hidden) * eta

In [7]:
print("Normalized input:", X, sep="\n")
print("\nActual output:", y, sep="\n")
print("\nPredicted output:", output, sep="\n")

Normalized input:
[[2. 9.]
 [1. 5.]
 [3. 6.]]

Actual output:
[[92.]
 [86.]
 [89.]]

Predicted output:
[[0.96201269]
 [0.96102261]
 [0.96197738]]
